FROM node:18 AS base
RUN npm i -g pnpm
WORKDIR /app

FROM base AS dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

FROM dependencies AS prisma
COPY prisma/ ./
RUN pnpx prisma generate

FROM prisma AS build
COPY . .
RUN pnpm run build


FROM dependencies AS deploy
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
CMD ["node", "dist/main.js"]
