version: "3.8"

volumes:
    postgres_data:

services:
  local-db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
        - ${POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=isbn
