name: Nestjs Test

on:
  push:
    branches: [ main, ci-test ]
  pull_request:
    branches: [ main ]

env:
  NODE_ENV: CI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - uses: actions/cache@v3
        id: cache-pnpm
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - run: pnpm install
        if: steps.cache-pnpm.outputs.cache-hit != 'true'
      - run: pnpm build
      - run: pnpm test
