name: Nestjs Test

on:
  push:
    branches: [ main, ci-test ]
  pull_request:
    branches: [ main ]

env:
  NODE_ENV: CI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
